### ISSUE TITLE
Error with taintAnalysis on lots of malware samples Error: Cannot find node:

### ISSUE THREAD

**Issue by maqsoodahmadjan** [sireum/amandroid#13]
I get an error Error: Cannot find node: .... with lots of malware samples. Here is one of the samples.

https://www.dropbox.com/s/pynkkw4gzkh8ffl/AnserverBot.apk?dl=0

**Comment by fgwei** [comment]
I downloaded your app but it seems the classes.dex has been deleted..

**Comment by fgwei** [comment]
fixed. you can try it out. and let me know any further exception.
