### ISSUE TITLE
About Amadroid setup

### ISSUE THREAD

**Issue by yongabc** [sireum/amandroid#16]
Hi, when I imported the Amandroid source (including Sireum repositories), there are many errors mark, 
The tutorial ("http://amandroid.sireum.org/docs/tutorial.html") says that I can "Just make sure you are using correct Java compiler version, and then clean all projects."

I sure that the Java compiler version is 1.8, but I still can't solve these errors.

![errors](https://cloud.githubusercontent.com/assets/8956715/5774654/1a6e2352-9dab-11e4-9600-1ae9b8a518d1.png)

**Comment by fgwei** [comment]
Could you send me all the full error message and other projects you have imported?

**Comment by yongabc** [comment]
@fgwei 

I have send these files to you via email

**Comment by fgwei** [comment]
it currently does not work on windows.

**Comment by yongabc** [comment]
Thinks, I will try it in ubuntu
