### ISSUE TITLE
No sbt/boot/scala in sireum-amandroid-build

### ISSUE THREAD

**Issue by vitaliiavdiienko** [sireum/amandroid#19]
Hi,
i am trying to compile amandroid in Eclipse, but got the following error:

`amandroid/sireum-amandroid-build/sbt/boot/scala-2.10.4/lib/scala-compiler.jar (No such file or directory)`

I didn't find anything about downloading of scala in the tutorial.

Thanks.

Best Rergards,
Vitalii

**Comment by fgwei** [comment]
Follow instructions here:
https://github.com/sireum/amandroid/issues/14

**Comment by vitaliiavdiienko** [comment]
Thanks
