### ISSUE TITLE
TaintAnalysis doesn't work on the latest commit

### ISSUE THREAD

**Issue by vitaliiavdiienko** [sireum/amandroid#21]
Hi all,

i have found out that TaintAnalysis stopped working on the latest development distribution of Sireum Amandroid. I have also checked the latest version of your GitHub project - the same result. I think some latest commits broke TaintAnalysis....
Everything works fine when I am using a stable distribution of Sireum Amandroid...

You can compare TaintAnalysis.txt files from runs on Stable and Development distributions on any DroidBench app... You can start with Callbacks_Button1.apk.

The thing is that I want to extend TaintAnalysis plugin and thus I need to work with the latest sources, which seems to be broken now.. Or just let me know on which commit it works.

Thank you in advance.

Best Regards,
Vitalii

**Comment by fgwei** [comment]
Hi Vitalii,

Sorry for the late reply.... (Basically I forget to reply :-P) Now it should work.

**Comment by vitaliiavdiienko** [comment]
Fixed! Thanks :+1:
