### ISSUE TITLE
could not download

### ISSUE THREAD

**Issue by magicislab** [sireum/amandroid#25]
HI, when i try to install amandroid in the terminal , i follow the instrcutions and type "sireum install amandroid" 
it always occurs below scenarios : 
![screenshot from 2015-03-29 14 26 54](https://cloud.githubusercontent.com/assets/10672049/6884337/abdb4b06-d61f-11e4-9f3f-d67e1586b1d7.png)

**Comment by fgwei** [comment]
I am sorry for the inconvenience. This problem caused by the university's network has some pro lem. We are trying to fix it.

**Comment by magicislab** [comment]
thanks a lot! I tried to download Amandroid many thimes but the network always seemed to have some problem. Hope it could fix it soon.

**Comment by fgwei** [comment]
You can Try this:
http://amandroid.sireum.org/docs/tutorial.html#troubleshooting
number 3
