### ISSUE TITLE
update the sireum - failure

### ISSUE THREAD

**Issue by magicislab** [sireum/amandroid#32]
HI, i try to update/execute the sireum , but it seems to always download failure. How to fix such problem? 
Could I download the newest version of java from the Oracle website ? 
![screen shot 2015-04-17 at 4 34 15 pm](https://cloud.githubusercontent.com/assets/10672049/7198512/9e1b6ca8-e51f-11e4-931b-18eb129d96cd.png)

**Comment by fgwei** [comment]
I think it's the network issue. You can run:
1. sireum clean
2. sireum 
Hope this help.
