### ISSUE TITLE
Could not find Eclipse Equinox launcher jar... when lauching sireumdev

### ISSUE THREAD

**Issue by magicislab** [sireum/amandroid#34]
Hi, fengguo.
I was trying to build up development platform as manual said. When it came to the third step "Launch Eclipse", it came up with following error: 
![screen shot 2015-04-18 at 11 33 50 pm](https://cloud.githubusercontent.com/assets/10672049/7216057/66310faa-e623-11e4-8216-22256fd96be8.png)
How could i solve such problem? 
Actually I tried to update the sireum, because I thought maybe there existed some plugins or folders that did not download from the sireum server. 
However, it implies that there is no update. 
![screen shot 2015-04-18 at 11 36 21 pm](https://cloud.githubusercontent.com/assets/10672049/7216067/c4558624-e623-11e4-96c1-17827b904453.png)

**Comment by fgwei** [comment]
The thing is probably the download is broken. So you need to do a 
sireum uninstall all
Then download again.
I don't know what happened to the university server recently, the downloading is not very stable.

**Comment by magicislab** [comment]
Ok, thanks.
