### ISSUE TITLE
bundle 'org sireum' cannot be resolved

### ISSUE THREAD

**Issue by magicyb** [sireum/amandroid#41]
Hi, fengguo. 
Thanks for your hard work on this project. Similar like CoolDeveloper1, I also hope to use Amandroid as a platform to build further analysis and useful plugins. 
I am testing the shortcake stable branches on Mac OSX 10.10 laptop. 
However,  I encountered some problem. 
I followed the instructions from the doc chapter 2.1, and imported the source of Amandroid into Eclipse. 
When building the project, it encountered one error. 
![screen shot 2015-06-17 at 4 27 56 pm](https://cloud.githubusercontent.com/assets/12742870/8202586/e27c8580-150d-11e5-866e-2be953044423.png)
So I really hope to understand how to solve such issue? Thanks a lot!

**Comment by fgwei** [comment]
Oh that is a new project (sireum-jawa-compiler) I am doing, and you don't need that to run amandroid.

**Comment by magicyb** [comment]
Hi, fengguo. 
You mean that I do not need to import files from project(sireum-java-compiler). That's right?

**Comment by fgwei** [comment]
yes

**Comment by magicyb** [comment]
Thanks!

**Comment by fgwei** [comment]
NP : P
