### ISSUE TITLE
Editing the Sinks And Sources file

### ISSUE THREAD

**Issue by mojtaba-esk** [sireum/amandroid#42]
Hi,

I am trying to track data flow from any input to the web servers (URL). I could not find any manual or example to do it. 
I leave these rules in the file:

Ljava/net/URLConnection;.setRequestProperty:(Ljava/lang/String;Ljava/lang/String;)V -> _SINK_
Ljava/net/Socket;.connect:(Ljava/net/SocketAddress;)V -> _SINK_
Ljava/net/URL;.openConnection:()Ljava/net/URLConnection; -> _SINK_
Landroid/app/Activity;.setResult:(ILandroid/content/Intent;)V -> _SINK_
Ljava/net/URLConnection;.getOutputStream:()Ljava/io/OutputStream; -> _SINK_

But I am not sure if that's all what required or there are other rules I need to add. Would you please kindly help me out?
Thank you in advance

**Comment by fgwei** [comment]
Sorry for the very late reply. I don't know why I didn't notice your question :p 
Yes, I think what you are doing correct.

**Comment by mojtaba-esk** [comment]
No problem :)
Thanks a lot for the reply.

On Wed, 3 Feb 2016 at 23:55 Fengguo Wei <notifications@github.com> wrote:

> Sorry for the very late reply. I don't know why I didn't notice your
> question :p
> Yes, I think what you are doing correct.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sireum/amandroid/issues/42#issuecomment-179516901>.
>
-- 
Kind regards,
Mojtaba
