### ISSUE TITLE
Run amandroid help me

### ISSUE THREAD

**Issue by Mac85** [sireum/amandroid#43]
I'am following this tutorial for use amandroid:
http://amandroid.sireum.org/software.html
Premise: I use an MacBook  Pro.
I have downloaded Sireum Strawberry version and to start it with terminal type the folder path and I get the menu:
![1](https://cloud.githubusercontent.com/assets/15186904/10567555/4f4049e4-7608-11e5-9e01-c79518c70ba3.jpg)
Now what do I have to type to start Android?

**Comment by fgwei** [comment]
sireum amandroid will give you next layer of options.

**Comment by Mac85** [comment]
I did not understand. If I want to start some tools, which command I type? Please let me you give an example?

**Comment by fgwei** [comment]
Have you check this link: http://amandroid.sireum.org/software.html#run-amandroid

**Comment by Mac85** [comment]
I write everything I've done:
I have downloaded Sireum Strawberry in this site " https://bintray.com/sireum/cli/stable/latest/view#files "
Then I run the terminal and I carry folder Sireum.
here you type the command: sireum amandroid 
The terminal writes: -bash: sireum: command not found
What is wrong?

**Comment by fgwei** [comment]
I think you haven't put the sireum into the PATH. Just do:
export PATH=/your_path/Sireum:$PATH

**Comment by Mac85** [comment]
I did like you said and now if I type: "sireum amandroid" works thanks.
Where can I find the commands that you can type to start the modes?

**Comment by fgwei** [comment]
Example commands:

$ sireum amandroid decompile /path/some.apk /outputPath
$ sireum amandroid taintAnalysis -m 12 -p -o /outputPath /path/some.apk /your_Amandroid_Home/taintAnalysis/sourceAndSinks/TaintSourcesAndSinks.txt

sireum amandroid will give you all the commands it allows.

**Comment by Mac85** [comment]
Ok thank you very much.
