### ISSUE TITLE
About Amandroid setup -- Java compiler version

### ISSUE THREAD

**Issue by lannan** [sireum/amandroid#45]
After I imported the Sireum repositories and Amandroid repository , there are many errors mark,
The tutorial ("http://amandroid.sireum.org/docs/tutorial.html") says that "Just make sure you are using correct Java compiler version, and then clean all projects."

I am not sure which Java compiler version is correct? 

Thanks.

**Comment by fgwei** [comment]
Now by default it will use the correct version which is 1.8. Or you can make a scrren shot to me to show your problems.

**Comment by lannan** [comment]
I tried version 1.8, 1.7. But still did not work...

![screenshot from 2015-12-02 00 06 04](https://cloud.githubusercontent.com/assets/4219642/11522743/a37718d8-9888-11e5-9eaa-6ec955b7cd8b.png)


![screenshot from 2015-12-02 00 07 49](https://cloud.githubusercontent.com/assets/4219642/11522753/bd6b5f06-9888-11e5-9b42-21bdfe524c18.png)

**Comment by lannan** [comment]
It seems only Sireum Parser is successfully imported.
But others are not.

**Comment by fgwei** [comment]
This is some problem with scala dependence.
You can delete all the projects (don't delete from disk, just from eclipse).
Than re import in order of prelude, parser, core, jawa, amandroid

**Comment by lannan** [comment]
Thanks! I import them orderly. 

But there is only one project not work. see the screenshot. Others are fine now. 

![screenshot from 2015-12-02 09 22 31](https://cloud.githubusercontent.com/assets/4219642/11533189/64df016e-98d6-11e5-8c2f-32c044464751.png)

**Comment by lannan** [comment]
the jawa project cannot successfully imported. others are fine now.

**Comment by fgwei** [comment]
Can you show me the error description page?

**Comment by lannan** [comment]
![screenshot from 2015-12-02 11 56 09](https://cloud.githubusercontent.com/assets/4219642/11537594/b8646012-98eb-11e5-90c0-15b2162bb098.png)


I am not sure whether this is the error description you want to check...

**Comment by lannan** [comment]
The log file is quite long...


[Untitled.txt](https://github.com/sireum/amandroid/files/49967/Untitled.txt)

**Comment by fgwei** [comment]
No, I means the Problems view :D

**Comment by lannan** [comment]
Is it this one?

![screenshot from 2015-12-02 12 11 14](https://cloud.githubusercontent.com/assets/4219642/11538011/d6415df4-98ed-11e5-8fda-4905277c3f8d.png)

**Comment by lannan** [comment]
![screenshot from 2015-12-02 12 11 14](https://cloud.githubusercontent.com/assets/4219642/11538036/f6557e22-98ed-11e5-9482-c2801bc4a7a1.png)

**Comment by lannan** [comment]
![screenshot from 2015-12-02 12 12 16](https://cloud.githubusercontent.com/assets/4219642/11538045/085f1254-98ee-11e5-8d20-f079a1d2a59a.png)

**Comment by fgwei** [comment]
Are you using eclipse provided by sireum?

**Comment by lannan** [comment]
Yes. I followed the instruction in "http://amandroid.sireum.org/docs/tutorial.html#setup-sireum-cli"

and use "sireum launch sireumdev -j "-Xms256m,-Xmx2048m" --args -clean" to launch eclipse.

**Comment by lannan** [comment]
The way I set up the sireum-ide is: (1) download Sireum Shortcake; (2) set up the path in .bashrc as the website says; (3) run sireum, what I get is:

![screenshot from 2015-12-02 12 25 00](https://cloud.githubusercontent.com/assets/4219642/11538366/ba95a46e-98ef-11e5-8a9a-5dd5e65f0d6f.png)

After that, I executed "sireum launch sireumdev -j "-Xms256m,-Xmx2048m" --args -clean".

Then download all the repos.

**Comment by fgwei** [comment]
for jawa and amandroid, you can pull the new code. It should remove some errors. And if there still some error showing, you can run: sireum list installed, and give a screen shot to me.

**Comment by lannan** [comment]
I pulled the two repos. But still did not work.
![screenshot from 2015-12-02 13 04 56](https://cloud.githubusercontent.com/assets/4219642/11539528/8f6e74d6-98f5-11e5-8fb5-d8695e24cc5f.png)

This is the screenshot after running "sireum list installed". Thanks!

![screenshot from 2015-12-02 13 06 07](https://cloud.githubusercontent.com/assets/4219642/11539522/8adb1348-98f5-11e5-93c0-4b82178300e5.png)

**Comment by fgwei** [comment]
Now I see the problem. You are using sireum stable version. But that is 7 months old, and the current amandroid uses a lot of new libs in the dev version. (I will update the documentation soon and sorry for the confussion.)

Now you can follow my following steps:
1. Download http://sireum.org/software.html#vanilla    "dev" version for your machine os.
2. You can replace your current sireum with the newly downloaded one.
3. run: sireum install "Sireum Amandroid Cli"
4. run: sireum launch sireumdev -j "-Xms256m,-Xmx2048m"
5. Set work space points to your current amandroid workspace.

**Comment by lannan** [comment]
Thanks a lot for your patience. I did the instructions you said. And there is only one project (sireum-jawa-test, under jawa repo) cannot be imported successfully.  

![screenshot from 2015-12-02 16 38 23](https://cloud.githubusercontent.com/assets/4219642/11545090/56a29aa6-9913-11e5-87a5-f199dee62f9c.png)

How to solve it? Thanks a lot!

**Comment by fgwei** [comment]
Just do a pull again on jawa and amandroid :P

**Comment by lannan** [comment]
Great! solved! Thanks so much for your help and patience!

**Comment by fgwei** [comment]
Normally I will work on develop branch or some topic branches. So if you want to contribute something please follow https://help.github.com/articles/fork-a-repo/

**Comment by lannan** [comment]
great. I will follow it.
