### ISSUE TITLE
Is Amandroid possible to analyze Android framework?

### ISSUE THREAD

**Issue by lannan** [sireum/amandroid#46]
Hi, I just wonder whether Amandroid is possible to analyze Android framework (e.g., system service)? As its website says, Amandroid is a static analyzer for Android apps; however, is it possible to analyze framework? 

If so, how to achieve it?

Thanks!

**Comment by fgwei** [comment]
It is possible, but challenging. Because jawa and amandroid is generic, and the program analysis technics are also generic. So you can tweak it by your own to achieve it.
I also have plan to add some framework analysis support, or you can wait for that.
