### ISSUE TITLE
Install vanilla Android dev version for linux64

### ISSUE THREAD

**Issue by Mac85** [sireum/amandroid#53]
Hello I downloaded "sireum-dev-linux64.tar.gz"
how do I install it? what are the commands?

**Comment by fgwei** [comment]
unzip it. Then follow this two steps:
1. http://sireum.org/software.html#strawberry
2. http://sireum.org/software.html#install

**Comment by Mac85** [comment]
I sireum extract. with the terminal took me into sireum folder and type its sireum install "Sireum Amandroid Cli" but the command was not found

**Comment by fgwei** [comment]
I think the problem is Sireum folder is not in your PATH, so either set the PATH, or in that folder ./sireum install "Sireum Amandroid Cli"

**Comment by Mac85** [comment]
I always fail. Invalid executable format




Inviato da iPhone

**Comment by fgwei** [comment]
Whats the OS of your host machine?

**Comment by Mac85** [comment]
Ubuntu 15.10

**Comment by fgwei** [comment]
Can you send me a screen shot, which help me to see the problem

**Comment by Mac85** [comment]
Ok
![image](https://cloud.githubusercontent.com/assets/15186904/13267476/b74d804a-da7d-11e5-96ac-cf1a28626d45.jpeg)

**Comment by fgwei** [comment]
It's a 32bit machine?

**Comment by Mac85** [comment]
Yes

Inviato da iPhone

**Comment by fgwei** [comment]
The sireum is a 64bit software, so it won't work on a 32bit machine.

**Comment by Mac85** [comment]
Ok 😞

Inviato da iPhone

> Il giorno 23 feb 2016, alle ore 23:12, Fengguo Wei <notifications@github.com> ha scritto:
> 
> The sireum is a 64bit software, so it won't work on a 32bit machine.
