### ISSUE TITLE
How to run the code I changed?

### ISSUE THREAD

**Issue by roylin1994** [sireum/amandroid#58]
Hi,
I changed the code in "TaintAnalysis.scala" for test:
`//println("Analysis result write into " + arFile)
    println("LinAnalysis result write into " + arFile)`
And how can i compile and run this change to run my analysis?
Is this can be implemented in eclipse?
Maybe it's a silly question,but hope your answer.

**Comment by fgwei** [comment]
There are two ways to test, one way is just run it in eclipse.

Another way is to build Amandroid first, then run, which I will provide the step by step walkthrough sometime tomorrow.

**Comment by roylin1994** [comment]
Thanks for your quick reply.

1. Can you introduce how to run it in eclipse to implement this change.And then I can run this command:`sireum amandroid taintAnalysis -mo INTENT_INJECTION -m 4 -o ./AnalysisResult/ ./APKFile/IC3Test.apk`

2.I'll wait for the another way's steps.

**Comment by fgwei** [comment]
The first way is not possible, unless amandroid team feel it's important to add to the official distribution.

So the second way is the walk-around, which allows you to build your own amandroid, and run any of your code.

**Comment by roylin1994** [comment]
Ok,I'll wait for your reply tomorrow.

**Comment by fgwei** [comment]
The way to build amandroid is in the following link:
https://github.com/fgwei/amandroid-build
