### ISSUE TITLE
Could not analyze apk

### ISSUE THREAD

**Issue by flankerhqd** [sireum/amandroid#9]
Running reachability analysis on some popular large apks get empty result. According to "verbose" logging option, components are all phantom so no result is returned, seems like some parsing error on apk.

attached trace:

```
[VERBOSE]layoutcallback--->Map()
[VERBOSE]layoutuser--->Map()
[VERBOSE]add phantom record com.***.activity.specialcare.QvipSpecialCareActivity
[VERBOSE]add phantom record com.***.av.service.QQServiceForAV
//.... all components are phantom
[VERBOSE]current all callbacks = Map()
[VERBOSE]LayoutClasses --> Map()
[NORMAL]Entry point calculation done.
[CRITICAL]************************************
```

One test sample apk attached as below: 
 http://box.myqsc.com/-07382619

**Comment by fgwei** [comment]
Hi Flanker, could send me the apk again to test. Currently I have updated our parsers. And just try to see whether you apk works fine know or not.

**Comment by flankerhqd** [comment]
Actually it's QQ apk, so just download it from http://gdown.baidu.com/data/wisegame/2c6a60c5cb96c593/QQ_182.apk :)

**Comment by fgwei** [comment]
It seems the QQ apk's resource file cannot be parsed. And following is the answer from apk-tool:
https://code.google.com/p/android-apktool/issues/detail?id=753
